TBASE=0
TUPPER=55

TEMPERATURE_CORE_1=data/temperatures_3932.csv
#TEMPERATURE_CORE_2=data/temperatures_49568.csv
#TEMPERATURE_CORE_3=data/temperatures_50430.csv
GDD_CORE_1=data/gddvalues_3932.csv
#GDD_CORE_2=data/gddvalues_49568.csv
#GDD_CORE_2=data/gddvalues_50430.csv
ACCUMGDD_1=data/3932accGdd.png
#ACCUMGDD_2=data/49568accGdd.png
#ACCUMGDD_3=data/50430accGdd.png

$SECONDTASK=data/SecondTask1.png

PREP=data

TEMPERATURE_LONG_MONTREAL=data/temperatures_5415.csv
GDD_LONG_MONTREAL=data/gddvalues_5415.csv
MONTREAL_REGRESSION=data/LinReg.png

TEMPERATURE_OTTAWA=data/temperatures_49568.csv
TEMPERATURE_MONTREAL=data/temperatures_51157.csv
TEMPERATURE_VICTORIA=data/temperatures_51337.csv
TEMPERATURE_ONE_YEAR = $(TEMPERATURE_OTTAWA) $(TEMPERATURE_MONTREAL) $(TEMPERATURE_VICTORIA)

GDD_OTTAWA=data/gddvalues_49568.csv
GDD_MONTREAL=data/gddvalues_51157.csv
GDD_VICTORIA=data/gddvalues_51337.csv
GDD_ONE_YEAR= $(GDD_OTTAWA) $(GDD_MONTREAL) $(GDD_VICTORIA)

TEMPERATURE_STJOHNS=data/temperatures_6720.csv
TEMPERATURE_CHARLESTON=data/temperatures_6599.csv
TEMPERATURE_GANDER=data/temperatures_6633.csv
TEMPERATURE_CORNER_BROOK=data/temperatures_6610.csv
TEMPERATURE_SWIFT_CURRENT=data/temperatures_6743.csv
TEMPERATURE_PLUM_POINT=data/temperatures_6688.csv
TEMPERATURE_TEN_YEAR = $(TEMPERATURE_STJOHNS) $(TEMPERATURE_CHARLESTON) $(TEMPERATURE_GANDER) $(TEMPERATURE_CORNER_BROOK) $(TEMPERATURE_SWIFT_CURRENT) $(TEMPERATURE_PLUM_POINT)

GDD_STJOHNS=data/gddvalues_6720.csv
GDD_CHARLESTON=data/gddvalues_6599.csv
GDD_GANDER=data/gddvalues_6633.csv
GDD_CORNER_BROOK=data/gddvalues_6610.csv
GDD_SWIFT_CURRENT=data/gddvalues_6743.csv
GDD_PLUM_POINT=data/gddvalues_6688.csv
GDD_TEN_YEAR= $(GDD_STJOHNS) $(GDD_CHARLESTON) $(GDD_GANDER) $(GDD_CORNER_BROOK) $(GDD_PLUM_POINT) $(GDD_SWIFT_CURRENT)

NLINFO=data/nlinfo.csv

NLWHEAT=data/nlwheatplot.png
NLSEED=data/nlseedplot.png
MAXMINPLOTS=data/MinMaxPlot.png
BOKEHPLOT=data/bokehplot.html

ALL: $(PREP) $(MAXMINPLOTS) $(NLSEED) $(BOKEHPLOT) $(NLWHEAT) $(MONTREAL_REGRESSION) $(SECONDTASK) $(ACCUMGDD_1) #$(ACCUMGDD_2) $(ACCUMGDD_3)

$(MONTREAL_REGRESSION): $(GDD_LONG_MONTREAL)
	./linearReg.py

$(GDD_LONG_MONTREAL): $(TEMPERATURE_LONG_MONTREAL)
	./gdd.py $(TEMPERATURE_LONG_MONTREAL) $(TBASE) $(TUPPER)

$(TEMPERATURE_LONG_MONTREAL):
	./downloadData.py 5415 1950 2010

$(GDD_STJOHNS): $(TEMPERATURE_STJOHNS)
	./gdd.py $(TEMPERATURE_STJOHNS) $(TBASE) $(TUPPER)

$(GDD_CHARLESTON): $(TEMPERATURE_CHARLESTON)
	./gdd.py $(TEMPERATURE_CHARLESTON) $(TBASE) $(TUPPER)

$(GDD_GANDER): $(TEMPERATURE_GANDER)
	./gdd.py $(TEMPERATURE_GANDER) $(TBASE) $(TUPPER)

$(GDD_CORNER_BROOK): $(TEMPERATURE_CORNER_BROOK)
	./gdd.py $(TEMPERATURE_CORNER_BROOK) $(TBASE) $(TUPPER)

$(GDD_SWIFT_CURRENT): $(TEMPERATURE_SWIFT_CURRENT)
	./gdd.py $(TEMPERATURE_SWIFT_CURRENT) $(TBASE) $(TUPPER)

$(GDD_PLUM_POINT): $(TEMPERATURE_PLUM_POINT)
	./gdd.py $(TEMPERATURE_PLUM_POINT) $(TBASE) $(TUPPER)

$(TEMPERATURE_CORNER_BROOK):
	./downloadData.py 6610 1995 2004

$(TEMPERATURE_SWIFT_CURRENT):
	./downloadData.py 6743 1995 2004

$(TEMPERATURE_PLUM_POINT):
	./downloadData.py 6688 1995 2004

$(TEMPERATURE_STJOHNS):
	./downloadData.py 6720 1995 2004

$(TEMPERATURE_CHARLESTON):
	./downloadData.py 6599 1995 2004

$(GDD_CORE_1): $(TEMPERATURE_CORE_1)
	./gdd.py $(TEMPERATURE_CORE_1) $(TBASE) $(TUPPER)

#$(GDD_CORE_2): $(TEMPERATURE_CORE_2)
#	./gdd.py $(TEMPERATURE_CORE_2) $(TBASE) $(TUPPER)

#$(GDD_CORE_3): $(TEMPERATURE_CORE_3)
#	./gdd.py $(TEMPERATURE_CORE_3) $(TBASE) $(TUPPER)

$(ACCUMGDD_1): $(GDD_CORE_1)
	./accumGdd.py 3932

$(SECONDTASK): $(GDD_CORE_1)
	./secondTask1.py 3932

#$(ACCUMGDD_2): $(GDD_CORE_2)
#	./accumGdd.py 49568

#$(ACCUMGDD_3): $(GDD_CORE_3)
#	./accumGdd.py 50430

$(TEMPERATURE_CORE_1):
	./downloadData.py 3932 1981 2016

#$(TEMPERATURE_CORE_2):
#	./downloadData.py 49568 1981 2016

#$(TEMPERATURE_CORE_3):
#	./downloadData.py 50430 1981 2016

$(TEMPERATURE_GANDER):
	./downloadData.py 6633 1995 2004

$(GDD_VICTORIA): $(TEMPERATURE_VICTORIA)
	./gdd.py $(TEMPERATURE_VICTORIA) $(TBASE) $(TUPPER)

$(GDD_MONTREAL): $(TEMPERATURE_MONTREAL)
	./gdd.py $(TEMPERATURE_MONTREAL) $(TBASE) $(TUPPER)

$(GDD_OTTAWA): $(TEMPERATURE_OTTAWA)
	./gdd.py $(TEMPERATURE_OTTAWA) $(TBASE) $(TUPPER)

$(BOKEHPLOT): $(GDD_ONE_YEAR)
	./bokehplot.py

$(NLSEED): $(NLINFO)
	./nlseedplot.py

$(NLWHEAT): $(NLINFO)
	./nlwheatplot.py

$(NLINFO): $(GDD_TEN_YEAR)
	./nlgrain.py

$(MAXMINPLOTS): $(TEMPERATURE_ONE_YEAR)
	./plotMinMax.py

$(TEMPERATURE_VICTORIA):
	./downloadData.py 51337 2016 2016

$(TEMPERATURE_MONTREAL):
	./downloadData.py 51157 2016 2016

$(TEMPERATURE_OTTAWA):
	./downloadData.py 49568 2016 2016

$(PREP):
	mkdir -p data

clean:
	rm -r data
	rm .DS_Store
	rm -r -f __pycache__
	rm -r .ipynb_checkpoints
	rm docs/.DS_Store
